# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 10:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Account Number/IBAN'),
        ),
        migrations.AlterField(
            model_name='account',
            name='sortcode',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Sort Code/Swift BIC'),
        ),
    ]
